import"./assets/toggle_theme-056aedf1.js";import"./assets/back_to_top-4d2101ad.js";import{a as b}from"./assets/vendor-1c5e86dd.js";const E="https://books-backend.p.goit.global/books/";async function H(){const e="category-list";return await b.get(`${E}${e}`)}async function S(){const e="top-books";return await b.get(`${E}${e}`)}async function w(e){const t="category?category=";return await b.get(`${E}${t}${e}`)}const _="/Smart-Foxes-Bookshelf/amazon.png",z="/Smart-Foxes-Bookshelf/books.png",R="/Smart-Foxes-Bookshelf/icon-close.svg",G="https://books-backend.p.goit.global/books/";async function F(e){try{const t=await b.get(`${G}${e}`);if(t.status===200)return t.data;throw new Error("Failed to fetch book details")}catch(t){console.error(t)}}function I(e){const t=document.createElement("div");t.classList.add("modal-backdrop"),t.addEventListener("click",s);const o=document.createElement("div");o.classList.add("modal");const n=document.createElement("button");n.classList.add("mdl-btn-icon-x"),n.innerHTML=`
        <svg class="mdl-icon-x" width="24" height="24">
        <use href="${R}"></use>
    </svg>
    `,n.addEventListener("click",s),window.addEventListener("keydown",a=>{a.key==="Escape"&&s()}),o.appendChild(n);const i=document.createElement("ul");i.classList.add("list","mdl-list"),o.appendChild(i),F(e).then(a=>{const u=document.createElement("li");i.appendChild(u);const l=document.createElement("img");l.classList.add("mdl-book-img"),l.alt="book",l.width=287,l.height=408;const j="URL_до_запасної_картинки.jpg";l.onerror=function(){l.src=j},l.src=a.book_image,u.appendChild(l);const k=document.createElement("li");i.appendChild(k);const L=document.createElement("h2");L.classList.add("mdl-book-name"),L.textContent=a.title,k.appendChild(L);const f=document.createElement("h3");f.classList.add("mdl-book-author"),f.textContent=`by ${a.author}`,k.appendChild(f);const y=document.createElement("p");y.classList.add("mdl-book-info"),y.textContent=a.description,k.appendChild(y);const p=document.createElement("ul");p.classList.add("list","mdl-link-list"),k.appendChild(p);const v=a.buy_links.find(c=>c.name==="Amazon");if(v){const c=document.createElement("li");p.appendChild(c);const r=document.createElement("a");r.classList.add("link"),r.href=v.url,r.target="_blank",r.innerHTML=`
        <img class="mdl-logo-amazon" src="${_}" alt="logo amazon" width="62" height="19">
    `,c.appendChild(r)}const B=a.buy_links.find(c=>c.name!=="Amazon");if(B){const c=document.createElement("li");p.appendChild(c);const r=document.createElement("a");r.classList.add("link"),r.href=B.url,r.target="_blank",r.innerHTML=`
        <img class="mdl-logo-book" src="${z}" alt="logo book" width="33" height="32">
    `,c.appendChild(r)}const d=document.createElement("button");d.classList.add("mdl-main-btn");const $=(JSON.parse(localStorage.getItem("shoppingList"))||[]).some(c=>c.title===a.title);$?d.textContent="Remove from the shopping list":d.textContent="Add to shopping list";const g=document.createElement("p");g.classList.add("confirmation-text"),g.innerHTML="Congratulations! You have added the book to the shopping list. To delete, press the button &rdquo;Remove from the shopping list&ldquo;.",g.style.display=$?"block":"none",d.addEventListener("click",c=>{c.stopPropagation(),N(a)?(d.textContent="Remove from the shopping list",g.style.display="block"):(d.textContent="Add to shopping list",g.style.display="none")}),o.appendChild(d),o.appendChild(g)}),t.appendChild(o),document.body.appendChild(t),document.body.style.overflow="hidden";function s(){t.removeEventListener("click",s),n.removeEventListener("click",s),window.removeEventListener("keydown",a=>{a.key==="Escape"&&s()}),t.remove(),document.body.style.overflow="auto"}}function N(e){let t=localStorage.getItem("shoppingList"),o=!1;t?t=JSON.parse(t):t=[];const n=t.findIndex(i=>i.title===e.title);return n===-1?(t.push(e),o=!0):t.splice(n,1),localStorage.setItem("shoppingList",JSON.stringify(t)),o}const O=document.querySelector(".categories-books"),m=document.querySelector(".categories-books-all"),C=document.querySelector(".categories-books-title"),T=document.querySelector(".loader");window.addEventListener("load",U);m.addEventListener("click",Y);O.addEventListener("click",J);m.addEventListener("click",K);m.addEventListener("click",Q);async function U(){T.style.display="none";try{const e=await S(),t=M(e.data);P(t)}catch(e){console.log(e)}}async function W(){T.style.display="none";try{const e=await S(),t=M(e.data);m.innerHTML=t}catch(e){console.log(e)}}function J(e){if(!e.target.classList.contains("categories-books-back-btn"))return;const t=e.target;W(),t.remove(),C.innerHTML='Best Sellers <span class="categories-books-title-accent">Books'}function M(e=[]){return e.map(({list_name:t,books:o})=>`
      <div class="categories-books-genre-title"> ${t}
        <ul class="categories-books-genre-all-books">
        ${V(o)}
        </ul>
        <button class="categories-books-btn">see more</button>
      </div>
      `).join("")}function V(e=[]){return e.map(({_id:t,list_name:o,author:n,book_image:i,title:s})=>`
      <li class="categories-books-genre-book" data-id="${t}" data-genre="${o}">
        <div class="categories-books-genre-book-img-thumb">
          <img class="categories-books-genre-book-img"
            src="${i}" alt="Title - '${s}'">
          <div class="categories-books-genre-book-hover">quick view </div>
        </div>
        <h2 class="categories-books-genre-book-title">${s}</h2>
        <h3 class="categories-books-genre-book-author">${n}</h3>
      </li>
      `).join("")}function P(e){m.insertAdjacentHTML("beforeend",e)}async function Y(e){if(!e.target.classList.contains("categories-books-btn"))return;const o=e.target.previousElementSibling.firstElementChild.dataset.genre,n=o.split(" "),i=n.splice(-1,1);C.innerHTML=`${n.join(" ")} <span class="categories-books-title-accent">${i.toString()}</span>`,C.insertAdjacentHTML("afterend",'<button class="categories-books-back-btn">back to Best Sellers</button>');try{const s=await w(o),a=A(s.data);x(a)}catch(s){console.log(s)}}function A(e=[]){return e.map(({_id:t,list_name:o,author:n,book_image:i,title:s})=>`
      <div class="categories-books-genre-all-books">
        <div class="categories-books-genre-books" data-id="${t}" data-genre="${o}">
          <div class="categories-books-genre-book-img-thumb">
            <img class="categories-books-genre-book-img"
              src="${i}" alt="Title - '${s}'">
              <div class="categories-books-genre-book-hover">quick view </div>
          </div>
          <h2 class="categories-books-genre-book-title">${s}</h2>
          <h3 class="categories-books-genre-book-author">${n}</h3>
        </div>
      </div> 
      `).join("")}function x(e){m.innerHTML=e}async function K(e){if(!e.target.closest(".categories-books-genre-book"))return;const o=e.target.closest(".categories-books-genre-book").dataset.id;await I(o)}async function Q(e){if(!e.target.closest(".categories-books-genre-books"))return;const o=e.target.closest(".categories-books-genre-books").dataset.id;await I(o)}const h={allCategoriesContainer:document.querySelector(".all-categories-container"),allCategoriesList:document.querySelector(".categories-list"),allCategoriesListItem:document.querySelector(".categories-list-item"),categoriesBook:document.querySelector(".categories-books-all"),categoriesBooksTitle:document.querySelector(".categories-books-title")};h.allCategoriesContainer.addEventListener("click",Z);h.allCategoriesContainer.addEventListener("click",q);function X(e){return e.map(({list_name:t})=>`<li class="categories-list-item js-categories-list-item" value="${t}" data-category='${t}'>${t}</li>`).join("")}H().then(e=>{h.allCategoriesList.insertAdjacentHTML("beforeend",X(e.data))}).catch(e=>console.log(e));function q(e){document.querySelector(".js-categories-list li:first-of-type")===e.currentTarget&&e.preventDefault(),e.target.tagName==="LI"&&(document.querySelectorAll(".js-categories-list li").forEach(s=>s.classList.remove("category-active")),e.target.classList.add("category-active"))}async function Z(e){q(e);const t=e.target;if(!(t.tagName==="LI"))return;const n=await w(t.attributes.value.nodeValue),i=A(n.data);x(i);const a=t.attributes.value.nodeValue.split(" "),u=a.splice(-1,1);h.categoriesBooksTitle.innerHTML=`${a.join(" ")} <span class="categories-books-title-accent">${u.toString()}</span>`}
//# sourceMappingURL=commonHelpers.js.map
