import "./js/BOOKS_API.js";
import "./js/header.js";
import "./js/toggle_theme.js";
import "./js/burger_menu.js";
import "./js/shopping.js";
import "./js/suport.js";
import "./js/pagination.js";
import "./js/back_to_top.js";
import "./js/pop_up.js";